staging

diff --git a/.github/workflows/health_check.yml b/.github/workflows/health_check.yml
--- a/.github/workflows/health_check.yml
+++ b/.github/workflows/health_check.yml
@@ -1,13 +1,16 @@
 name: Django CI
-permissions: 
-  contents: read
-  issues: write
 
 on:
   push:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]
+
+# TODO: Add a scheduler
+# on:
+#   schedule:
+#     - cron:  '*/15 * * * *'
+
 
 jobs:
   build:
@@ -27,94 +30,73 @@ jobs:
       with:
         python-version: ${{ matrix.python-version }}
         
-    # - name: Start Health Check
-    #   run: |
-    #     echo 'Start Health check'
+    - name: Start Health Check
+      run: |
+        echo 'Start Health check'
         
-    # - name: File existence check
-    #   id: check_files
-    #   uses: andstor/file-existence-action@v1
-    #   with:
-    #     files: "README.md, requirements.txt"
-        
-    # - name: File check    
-    #   if: steps.check_files.outputs.files_exits == 'true'
-    #   run: |
-    #     echo Required files present
-    - uses: actions/checkout@v2
-    - name: Create issue
-      # if: steps.check_files.outputs.files_exits == 'false'
-      uses: actions/checkout@v2
-
-      # uses: dacbd/create-issue-action@main
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    - name: File existence check
+      id: check_files
+      uses: andstor/file-existence-action@v1
       with:
-        # title: Requirements fail
-        # token: ${{secrets.GITHUB_TOKEN}}
-        assignees: ${{github.actor}}
-        milestone: 1
-        update_existing: true
-        search_existing: all
+        files: "README.md, requirements.txt"
+        
+    - name: File check    
+      if: steps.check_files.outputs.files_exits == 'true'
+      run: |
+        echo Required files present
 
-        # labels: update-needed
-        # body: Workflow failed for commit ${{github.sha}}
-        # assignees: ${{github.actor}}
-        # update_existing: true
-        # search_exisiting: open
-
-    # - name: Files do not exist  
-    #   if: steps.check_files.outputs.files_exits == 'false'
-    #   run: |
-    #     exit 1    
-    #     'echo Required files are missing'    
-
-      
-      # run: |
-      #   exit 1    
-      #   'echo Required files are missing'
-      #   'echo Created issue number ${{ steps.create-issue.outputs.number }}'
-      #   'echo Created ${{ steps.create-issue.outputs.url }}'
-          
+  # TODO: add a issue creator for when this fails
+    - name: Files do not exist  
+      if: steps.check_files.outputs.files_exits == 'false'
+      run: |
+        exit 1    
+        'echo Required files are missing'    
  
-  # job1:
-  #   name: Check Style and run tests
-  #   runs-on: ubuntu-latest
-  #   strategy:
-  #     max-parallel: 4
-  #     matrix:
-  #         python-version: [3.7]
+  job1:
+    name: Check Style and run tests
+    runs-on: ubuntu-latest
+    strategy:
+      max-parallel: 4
+      matrix:
+          python-version: [3.7]
 
 
-  #   needs: [build]
-  #   steps: 
-  #   - uses: actions/checkout@v3
+    needs: [build]
+    steps: 
+    - uses: actions/checkout@v3
     
-  #   - name: Set up Python ${{ matrix.python-version }}
-  #     uses: actions/setup-python@v3
-  #     with:
-  #       python-version: ${{ matrix.python-version }}
+    - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v3
+      with:
+        python-version: ${{ matrix.python-version }}
         
-  #   - name: Start Health Check
-  #     run: |
-  #       echo 'Start Health check'
-  #   - name: Installing Dependencies
-  #     run: | 
-  #         python -m pip install --upgrade pip   
-  #         pip install -r requirements.txt -U
+    - name: Start Health Check
+      run: |
+        echo 'Start Health check'
+    - name: Installing Dependencies
+      run: | 
+          python -m pip install --upgrade pip   
+          pip install -r requirements.txt -U
         
-  #   - name: Run migrations
-  #     run: python manage.py migrate   
-  #   - name: Lint with flake8
-  #     working-directory: blog 
-  #     run: |
-  #       # stop the build if there are Python syntax errors or undefined names
-  #       flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-  #       # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-  #       flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
-  #   - name: Run tests
-  #     run: |
-  #       python ./manage.py test
+    - name: Run migrations
+      run: python manage.py migrate   
+    - name: Lint with flake8
+      working-directory: blog 
+      run: |
+        # stop the build if there are Python syntax errors or undefined names
+        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
+        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
+        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+
+    - name: Coverage report
+      run: |
+        pip install coverage
+        coverage run manage.py test
+        coverage report    
+
+    - name: Run tests
+      run: |
+        python ./manage.py test
         
         
         
