failing step file check

diff --git a/.github/workflows/health_check.yml b/.github/workflows/health_check.yml
--- a/.github/workflows/health_check.yml
+++ b/.github/workflows/health_check.yml
@@ -22,14 +22,21 @@ jobs:
       uses: actions/setup-python@v3
       with:
         python-version: ${{ matrix.python-version }}
-        
-    - name: Failing step
-      id: demo
-      run: exit 1
 
-    - name: The demo step has failed
-      if: ${{ failure() && steps.demo.conclusion == 'failure' }}
-      run: echo 'Job failed'
+    - name: File existence check
+      id: check_files
+      uses: andstor/file-existence-action@v1
+      with:
+        files: "README.md, requirements.txt"
+        allow_failure: true
+        
+    # - name: Failing step
+    #   id: demo
+    #   run: exit 1
+
+    # - name: The demo step has failed
+    #   if: ${{ failure() && steps.demo.conclusion == 'failure' }}
+    #   run: echo 'Job failed'
 
         
         
